name: Build Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Export Android APK
        uses: dulvui/godot-android-export@v4.1.0
        with:
          godot-version: 4.2.2
          working-directory: ./

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: apk/*.apk
